In [26]:
import numpy

In [27]:
candidate_points = {
    "iris_sertosa": numpy.array([5.8, 4.0, 1.2, 0.2]),
    "iris_versicolor": numpy.array([6.1, 2.8, 4.0, 1.3]),
    "iris_virginica": numpy.array([6.3, 2.7, 4.9, 1.8]),
}

In [28]:
def find_candidate(point: numpy.ndarray) -> str:
    distance1: float = numpy.dot(point.T, candidate_points["iris_sertosa"])
    distance2: float = numpy.dot(point.T, candidate_points["iris_versicolor"])
    distance3: float = numpy.dot(point.T, candidate_points["iris_virginica"])

    min_distance: float = min([distance1, distance2, distance3])
    print(numpy.array([distance1, distance2, distance3, min_distance]))
    if distance1 == min_distance:
        return "iris_sertosa"
    elif distance2 == min_distance:
        return "iris_versicolor"
    elif distance3 == min_distance:
        return "iris_virginica"
    else:
        raise Exception()

    


In [29]:
with open("iris.data") as file:
    for line in file:
        line = line.strip().lower()
        numbers = list(map(float, line.split(",")[:-1]))
        point = numpy.array(numbers)

        print()
        
        print(find_candidate(point), end= "\t")
        print(*list(point), sep = ",")


[45.3  46.77 48.8  45.3 ]
iris_sertosa	5.1,3.5,1.4,0.2

[42.14 44.15 46.19 42.14]
iris_sertosa	4.9,3.0,1.4,0.2

[41.66 43.09 44.98 41.66]
iris_sertosa	4.7,3.2,1.3,0.2

[40.92 43.   45.06 40.92]
iris_sertosa	4.6,3.1,1.5,0.2

[45.12 46.44 48.44 45.12]
iris_sertosa	5.0,3.6,1.4,0.2

[49.04 51.18 53.6  49.04]
iris_sertosa	5.4,3.9,1.7,0.4

[42.02 43.57 45.56 42.02]
iris_sertosa	4.6,3.4,1.4,0.3

[44.44 46.28 48.39 44.44]
iris_sertosa	5.0,3.4,1.5,0.2

[38.84 40.82 42.77 38.84]
iris_sertosa	4.4,2.9,1.4,0.2

[42.64 44.7  46.77 42.64]
iris_sertosa	4.9,3.1,1.5,0.1

[47.96 49.56 51.72 47.96]
iris_sertosa	5.4,3.7,1.5,0.2

[43.4  45.46 47.62 43.4 ]
iris_sertosa	4.8,3.4,1.6,0.2

[41.54 43.41 45.38 41.54]
iris_sertosa	4.8,3.0,1.4,0.1

[38.28 39.16 40.76 38.28]
iris_sertosa	4.3,3.0,1.1,0.1

[51.12 51.64 53.58 51.12]
iris_sertosa	5.8,4.0,1.2,0.2

[52.54 53.61 55.86 52.54]
iris_sertosa	5.7,4.4,1.5,0.4

[48.56 49.58 51.64 48.56]
iris_sertosa	5.4,3.9,1.3,0.4

[45.32 46.9  48.98 45.32]
iris_sertosa	5.1,3.5,